# Generated by Django 6.0.7 on 2026-07-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_remove_fornecedor_endereco_fornecedor_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
