# Generated by Django 4.2 on 2026-04-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ultimo_pedido',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
