# Generated by Django 4.2 on 2026-04-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('products', '0002_produto_ultimo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='fornecedores.fornecedor'),
        ),
    ]
